-- Academic modules schema for NCF COE Blockchain Grade System
-- Run in Supabase SQL editor (safe to re-run).

create table if not exists public.faculty_records (
  id text primary key,
  name text not null,
  dept text not null,
  rank text,
  status text,
  created_at timestamp with time zone default now()
);

create table if not exists public.teaching_loads (
  id bigint generated by default as identity primary key,
  faculty_id text not null references public.faculty_records(id) on delete cascade,
  faculty text not null,
  subject text not null,
  section text not null,
  units integer,
  schedule text,
  created_at timestamp with time zone default now()
);

create table if not exists public.curriculum_subjects (
  code text primary key,
  title text not null,
  units integer,
  program text,
  year text,
  semester text,
  created_at timestamp with time zone default now()
);

create table if not exists public.sections (
  id text primary key,
  name text not null,
  program text,
  year text,
  semester text,
  created_at timestamp with time zone default now()
);

create table if not exists public.section_subjects (
  section_id text not null references public.sections(id) on delete cascade,
  subject_code text not null,
  created_at timestamp with time zone default now(),
  primary key (section_id, subject_code)
);

create table if not exists public.section_students (
  section_id text not null references public.sections(id) on delete cascade,
  student_id text not null,
  created_at timestamp with time zone default now(),
  primary key (section_id, student_id)
);

insert into public.curriculum_subjects (code, title, units, program, year, semester)
values
  ('Math 111', 'Calculus 1 (Differential Calculus)', 3, 'BSCpE', '1st', '1st'),
  ('Chem 111', 'Chemistry for Engineers', 3, 'BSCpE', '1st', '1st'),
  ('CpE 111', 'Computer Engineering as a Discipline', 3, 'BSCpE', '1st', '1st'),
  ('CpE 112', 'Programming Logic and Design', 3, 'BSCpE', '1st', '1st'),
  ('GEC 2', 'Understanding the Self', 3, 'BSCpE', '1st', '1st'),
  ('NSTP 1', 'CWTS/ROTC 1', 3, 'BSCpE', '1st', '1st'),
  ('Math 122', 'Calculus 2 (Integral Calculus)', 3, 'BSCpE', '1st', '2nd'),
  ('Math 123', 'Engineering Data Analysis', 3, 'BSCpE', '1st', '2nd'),
  ('Phys 121', 'Physics for Engineers (Calculus-based)', 4, 'BSCpE', '1st', '2nd'),
  ('CpE 121', 'Discrete Mathematics', 3, 'BSCpE', '1st', '2nd'),
  ('CpE 122', 'Object-Oriented Programming', 3, 'BSCpE', '1st', '2nd'),
  ('Math 213', 'Differential Equations', 3, 'BSCpE', '2nd', '1st'),
  ('CpE 211', 'Data Structures and Algorithms', 2, 'BSCpE', '2nd', '1st'),
  ('CpE 212', 'Computer-Aided Drafting', 2, 'BSCpE', '2nd', '1st'),
  ('CpE 213', 'Engineering Economics', 3, 'BSCpE', '2nd', '1st'),
  ('CpE 214', 'Fundamentals of Electrical Circuits', 4, 'BSCpE', '2nd', '1st'),
  ('CpE 221', 'Software Design', 4, 'BSCpE', '2nd', '2nd'),
  ('CpE 222', 'Fundamentals of Electronic Circuits', 4, 'BSCpE', '2nd', '2nd'),
  ('CpE 223', 'Numerical Methods', 3, 'BSCpE', '2nd', '2nd'),
  ('CpE 311', 'Logic Circuits and Design', 4, 'BSCpE', '3rd', '1st'),
  ('CpE 312', 'Operating Systems', 3, 'BSCpE', '3rd', '1st'),
  ('CpE 313', 'Data and Digital Communications', 3, 'BSCpE', '3rd', '1st'),
  ('CpE 314', 'Feedback and Control Systems', 3, 'BSCpE', '3rd', '1st'),
  ('CpE 315', 'Fundamentals of Mixed Signals and Sensors', 3, 'BSCpE', '3rd', '1st'),
  ('CpE 316', 'Introduction to HDL', 1, 'BSCpE', '3rd', '1st'),
  ('CpE 317', 'Computer Engineering Drafting and Design', 1, 'BSCpE', '3rd', '1st'),
  ('CpE 318', 'System & Network Administration 1', 3, 'BSCpE', '3rd', '1st'),
  ('CpE 319', 'Software Development 1', 3, 'BSCpE', '3rd', '1st'),
  ('CpE 321', 'Computer Networks and Security', 4, 'BSCpE', '3rd', '2nd'),
  ('CpE 322', 'Microprocessors', 4, 'BSCpE', '3rd', '2nd'),
  ('CpE 323', 'CpE Laws and Professional Practice', 3, 'BSCpE', '3rd', '2nd'),
  ('CpE 324', 'Basic Occupational Safety and Health', 3, 'BSCpE', '3rd', '2nd'),
  ('CpE 325', 'System & Network Administration 2', 3, 'BSCpE', '3rd', '2nd'),
  ('CpE 326', 'Software Development 2', 3, 'BSCpE', '3rd', '2nd'),
  ('CpE 327', 'Methods of Research', 2, 'BSCpE', '3rd', '2nd'),
  ('GEC 5', 'Contemporary World', 3, 'BSCpE', '3rd', '2nd'),
  ('CpE 328', 'On-the-Job Training (min. of 240 hrs.)', 3, 'BSCpE', '4th', 'Summer'),
  ('CpE 411', 'Embedded Systems', 4, 'BSCpE', '4th', '1st'),
  ('CpE 412', 'Computer Architecture and Organization', 4, 'BSCpE', '4th', '1st'),
  ('CpE 413', 'Digital Signal Processing', 4, 'BSCpE', '4th', '1st'),
  ('CpE 414', 'Emerging Technologies in CpE', 3, 'BSCpE', '4th', '1st'),
  ('CpE 415', 'Computer Engineering Practice and Design 1', 1, 'BSCpE', '4th', '1st'),
  ('CpE 416', 'System & Network Administration 3', 3, 'BSCpE', '4th', '1st'),
  ('CpE 417', 'Environmental Science and Engineering', 3, 'BSCpE', '4th', '1st'),
  ('CpE 421', 'Computer Engineering Practice and Design 2', 2, 'BSCpE', '4th', '2nd'),
  ('CpE 422', 'Seminars and Fieldtrips', 1, 'BSCpE', '4th', '2nd'),
  ('CpE 423', 'Technopreneurship 101', 3, 'BSCpE', '4th', '2nd'),
  ('CpE 424', 'Software Development 3', 3, 'BSCpE', '4th', '2nd'),
  ('GEC 8', 'Ethics', 3, 'BSCpE', '4th', '2nd'),
  -- BSCE
  ('BSCE-Math 111', 'Calculus 1 (Differential Calculus)', 4, 'BSCE', '1st', '1st'),
  ('BSCE-Chem 111', 'Chemistry for Engineers', 4, 'BSCE', '1st', '1st'),
  ('CE 111', 'Civil Engineering Orientation', 2, 'BSCE', '1st', '1st'),
  ('BSCE-Math 122', 'Calculus 2 (Integral Calculus)', 4, 'BSCE', '1st', '2nd'),
  ('BSCE-Phys 121', 'Physics for Engineers (Calculus-Based)', 4, 'BSCE', '1st', '2nd'),
  ('CE 121', 'Engineering Drawing and Plans', 1, 'BSCE', '1st', '2nd'),
  ('Comp 121', 'Computer Fundamentals and Programming', 2, 'BSCE', '1st', '2nd'),
  ('BSCE-Math 213', 'Differential Equations', 3, 'BSCE', '2nd', '1st'),
  ('Mech 211', 'Static of Rigid Bodies', 3, 'BSCE', '2nd', '1st'),
  ('CE 211', 'Computer-Aided Drafting', 2, 'BSCE', '2nd', '1st'),
  ('CE 212', 'Fundamentals of Surveying', 4, 'BSCE', '2nd', '1st'),
  ('CE 213', 'Engineering Economics', 3, 'BSCE', '2nd', '1st'),
  ('CE 214', 'Engineering Management', 2, 'BSCE', '2nd', '1st'),
  ('Math 224', 'Engineering Data Analysis', 3, 'BSCE', '2nd', '2nd'),
  ('Mech 222', 'Dynamics of Rigid Bodies', 2, 'BSCE', '2nd', '2nd'),
  ('Mech 223', 'Mechanics of Deformable Bodies', 4, 'BSCE', '2nd', '2nd'),
  ('CE 221', 'Geology for Civil Engineers', 3, 'BSCE', '2nd', '2nd'),
  ('CE 222', 'Construction Materials and Testing', 3, 'BSCE', '2nd', '2nd'),
  ('Math 315', 'Numerical Solutions to CE Problems', 4, 'BSCE', '3rd', '1st'),
  ('CE 311', 'Structural Theory', 4, 'BSCE', '3rd', '1st'),
  ('CE 312', 'Highway and Railroad Engineering', 3, 'BSCE', '3rd', '1st'),
  ('CE 313', 'Engineering Utilities 1 (Electrical)', 3, 'BSCE', '3rd', '1st'),
  ('CE 314', 'Engineering Utilities 2 (Mechanical)', 3, 'BSCE', '3rd', '1st'),
  ('CE 315', 'Environmental Science and Engineering', 3, 'BSCE', '3rd', '1st'),
  ('CE 316', 'Building System Design', 3, 'BSCE', '3rd', '1st'),
  ('CE 321', 'Principles of Reinforced/Prestressed Concrete', 4, 'BSCE', '3rd', '2nd'),
  ('CE 322', 'Principles of Steel Design', 3, 'BSCE', '3rd', '2nd'),
  ('CE 323', 'Principle of Transportation Engineering', 3, 'BSCE', '3rd', '2nd'),
  ('CE 324', 'Hydraulics', 5, 'BSCE', '3rd', '2nd'),
  ('CE 325', 'Hydrology', 2, 'BSCE', '3rd', '2nd'),
  ('CE 326', 'CE Laws, Ethics and Contracts', 2, 'BSCE', '3rd', '2nd'),
  ('CE 327', 'Technopreneurship 101', 3, 'BSCE', '3rd', '2nd'),
  ('CE 328', 'Quantity Surveying', 2, 'BSCE', '3rd', '2nd'),
  ('CE 329', 'On-the-Job Training (min. of 240 hrs.)', 3, 'BSCE', '4th', 'Summer'),
  ('CE 411', 'Reinforced and Prestressed Concrete Design', 4, 'BSCE', '4th', '1st'),
  ('CE 412', 'Design of Steel Structures', 4, 'BSCE', '4th', '1st'),
  ('CE 413', 'Geotechnical Engineering 1 (Soils Mechanics)', 4, 'BSCE', '4th', '1st'),
  ('CE 414', 'Construction Methods & Project Management', 4, 'BSCE', '4th', '1st'),
  ('CE 415', 'CE Laws and Professional Practice', 3, 'BSCE', '4th', '1st'),
  ('CE 421', 'Foundation and Retaining Wall Design', 3, 'BSCE', '4th', '2nd'),
  ('CE 422', 'Earthquake Engineering', 3, 'BSCE', '4th', '2nd'),
  ('CE 423', 'Computer Softwares in Structural Analysis', 3, 'BSCE', '4th', '2nd'),
  ('CE 424', 'CE Project 2 (Research Writing)', 3, 'BSCE', '4th', '2nd'),
  -- BSGE
  -- BSGE
  ('BSGE-Math 111', 'Calculus 1 (Differential Calculus)', 4, 'BSGE', '1st', '1st'),
  ('GE 111', 'General Surveying 1', 3, 'BSGE', '1st', '1st'),
  ('GE 112', 'Safety Management', 1, 'BSGE', '1st', '1st'),
  ('GE 113', 'Computer Fundamentals and Programming', 3, 'BSGE', '1st', '1st'),
  ('GE 114', 'Engineering Data Analysis', 3, 'BSGE', '1st', '1st'),
  ('GE 115', 'Computer-Aided Drafting', 2, 'BSGE', '1st', '1st'),
  ('GE 116', 'Into the Laws on Private and Public Lands', 2, 'BSGE', '1st', '1st'),
  ('BSGE-Math 122', 'Calculus 2 (Integral Calculus)', 4, 'BSGE', '1st', '2nd'),
  ('BSGE-Phys 121', 'Physics for Engineers (Calculus-based)', 4, 'BSGE', '1st', '2nd'),
  ('GE 121', 'Cartography', 3, 'BSGE', '1st', '2nd'),
  ('GE 122', 'General Surveying 2', 4, 'BSGE', '1st', '2nd'),
  ('GE 123', 'Principles of Geology', 3, 'BSGE', '1st', '2nd'),
  ('BSGE-Math 123', 'Differential Equations', 3, 'BSGE', '2nd', '1st'),
  ('BSGE-Mech 211', 'Engineering Mechanics', 3, 'BSGE', '2nd', '1st'),
  ('GE 211', 'Geometric Geodesy', 3, 'BSGE', '2nd', '1st'),
  ('GE 212', 'Engineering Surveys', 4, 'BSGE', '2nd', '1st'),
  ('GE 213', 'Theory of Errors and Adjustments', 3, 'BSGE', '2nd', '1st'),
  ('GE 214', 'Electrical & Electronics Engineering for GE', 3, 'BSGE', '2nd', '1st')

on conflict (code) do update
set
  title = excluded.title,
  units = excluded.units,
  program = excluded.program,
  year = excluded.year,
  semester = excluded.semester;

create table if not exists public.enrollment_records (
  id text primary key,
  name text not null,
  program text,
  section text,
  status text,
  adviser text,
  created_at timestamp with time zone default now()
);

create table if not exists public.grade_sheets (
  id bigint generated by default as identity primary key,
  subject text not null,
  section text not null,
  period text not null,
  last_updated text,
  status text,
  created_at timestamp with time zone default now()
);

create table if not exists public.students (
  id text not null,
  name text not null,
  subj text not null,
  prof text not null,
  prelim integer,
  midterm integer,
  semi integer,
  final integer,
  status text,
  upload_method text,
  encoded_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  primary key (id, subj)
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  code text not null,
  prof text not null,
  title text,
  created_at timestamp with time zone default now(),
  unique (code, prof)
);

create table if not exists public.user_profiles (
  id text primary key,
  name text not null,
  role text,
  avatar_url text,
  created_at timestamp with time zone default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  prof text not null,
  user_id text,
  action text not null,
  time timestamp with time zone default now(),
  ip_address text,
  user_agent text,
  device text,
  os text,
  created_at timestamp with time zone default now()
);

create table if not exists public.audit_presence (
  user_id text primary key,
  last_seen timestamp with time zone default now(),
  ip_address text,
  user_agent text,
  device text,
  os text,
  status text,
  updated_at timestamp with time zone default now()
);

alter table public.faculty_records enable row level security;
alter table public.teaching_loads enable row level security;
alter table public.curriculum_subjects enable row level security;
alter table public.sections enable row level security;
alter table public.section_subjects enable row level security;
alter table public.section_students enable row level security;
alter table public.enrollment_records enable row level security;
alter table public.grade_sheets enable row level security;
alter table public.subjects enable row level security;
alter table public.students enable row level security;
alter table public.user_profiles enable row level security;
alter table public.audit_logs enable row level security;
alter table public.audit_presence enable row level security;

-- Example read policies (adjust for your roles/claims)
drop policy if exists "faculty_records_read" on public.faculty_records;
create policy "faculty_records_read" on public.faculty_records
  for select using (true);

drop policy if exists "faculty_records_insert" on public.faculty_records;
create policy "faculty_records_insert" on public.faculty_records
  for insert with check (auth.jwt()->>'email' = id);

drop policy if exists "faculty_records_update" on public.faculty_records;
create policy "faculty_records_update" on public.faculty_records
  for update using (auth.jwt()->>'email' = id);

drop policy if exists "faculty_records_delete" on public.faculty_records;
create policy "faculty_records_delete" on public.faculty_records
  for delete using (
    auth.jwt()->>'email' = id
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "teaching_loads_read" on public.teaching_loads;
create policy "teaching_loads_read" on public.teaching_loads
  for select using (true);

drop policy if exists "curriculum_subjects_read" on public.curriculum_subjects;
create policy "curriculum_subjects_read" on public.curriculum_subjects
  for select using (true);

drop policy if exists "curriculum_subjects_insert" on public.curriculum_subjects;
create policy "curriculum_subjects_insert" on public.curriculum_subjects
  for insert with check (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "curriculum_subjects_update" on public.curriculum_subjects;
create policy "curriculum_subjects_update" on public.curriculum_subjects
  for update using (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "sections_read" on public.sections;
create policy "sections_read" on public.sections
  for select using (true);

drop policy if exists "sections_insert" on public.sections;
create policy "sections_insert" on public.sections
  for insert with check (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "sections_update" on public.sections;
create policy "sections_update" on public.sections
  for update using (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "sections_delete" on public.sections;
create policy "sections_delete" on public.sections
  for delete using (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "audit_logs_read" on public.audit_logs;
create policy "audit_logs_read" on public.audit_logs
  for select using (true);

drop policy if exists "audit_logs_insert" on public.audit_logs;
create policy "audit_logs_insert" on public.audit_logs
  for insert with check (auth.uid() is not null);

drop policy if exists "audit_presence_read" on public.audit_presence;
create policy "audit_presence_read" on public.audit_presence
  for select using (true);

drop policy if exists "audit_presence_insert" on public.audit_presence;
create policy "audit_presence_insert" on public.audit_presence
  for insert with check (auth.uid() is not null);

drop policy if exists "audit_presence_update" on public.audit_presence;
create policy "audit_presence_update" on public.audit_presence
  for update using (auth.uid() is not null);

drop policy if exists "section_subjects_read" on public.section_subjects;
create policy "section_subjects_read" on public.section_subjects
  for select using (true);

drop policy if exists "section_subjects_insert" on public.section_subjects;
create policy "section_subjects_insert" on public.section_subjects
  for insert with check (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "section_subjects_update" on public.section_subjects;
create policy "section_subjects_update" on public.section_subjects
  for update using (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "section_subjects_delete" on public.section_subjects;
create policy "section_subjects_delete" on public.section_subjects
  for delete using (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "section_students_read" on public.section_students;
create policy "section_students_read" on public.section_students
  for select using (true);

drop policy if exists "section_students_insert" on public.section_students;
create policy "section_students_insert" on public.section_students
  for insert with check (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "section_students_update" on public.section_students;
create policy "section_students_update" on public.section_students
  for update using (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "section_students_delete" on public.section_students;
create policy "section_students_delete" on public.section_students
  for delete using (auth.jwt()->'user_metadata'->>'role' = 'dean');

drop policy if exists "enrollment_records_read" on public.enrollment_records;
create policy "enrollment_records_read" on public.enrollment_records
  for select using (true);

drop policy if exists "grade_sheets_read" on public.grade_sheets;
create policy "grade_sheets_read" on public.grade_sheets
  for select using (true);

drop policy if exists "subjects_read" on public.subjects;
create policy "subjects_read" on public.subjects
  for select using (true);

drop policy if exists "subjects_insert" on public.subjects;
create policy "subjects_insert" on public.subjects
  for insert with check (auth.jwt()->>'email' = prof);

drop policy if exists "subjects_update" on public.subjects;
create policy "subjects_update" on public.subjects
  for update using (auth.jwt()->>'email' = prof);

drop policy if exists "subjects_delete" on public.subjects;
create policy "subjects_delete" on public.subjects
  for delete using (
    auth.jwt()->>'email' = prof
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "students_read" on public.students;
create policy "students_read" on public.students
  for select using (true);

drop policy if exists "students_insert" on public.students;
create policy "students_insert" on public.students
  for insert with check (auth.jwt()->>'email' = prof);

drop policy if exists "students_update" on public.students;
create policy "students_update" on public.students
  for update using (auth.jwt()->>'email' = prof);

drop policy if exists "students_delete" on public.students;
create policy "students_delete" on public.students
  for delete using (
    auth.jwt()->>'email' = prof
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "user_profiles_read" on public.user_profiles;
create policy "user_profiles_read" on public.user_profiles
  for select using (
    auth.jwt()->>'email' = id
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "user_profiles_insert" on public.user_profiles;
create policy "user_profiles_insert" on public.user_profiles
  for insert with check (
    auth.jwt()->>'email' = id
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "user_profiles_update" on public.user_profiles;
create policy "user_profiles_update" on public.user_profiles
  for update using (
    auth.jwt()->>'email' = id
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );
