-- Academic modules schema for NCF COE Blockchain Grade System
-- Run in Supabase SQL editor (safe to re-run).

create table if not exists public.faculty_records (
  id text primary key,
  name text not null,
  dept text not null,
  rank text,
  status text,
  created_at timestamp with time zone default now()
);

create table if not exists public.teaching_loads (
  id bigint generated by default as identity primary key,
  faculty_id text not null references public.faculty_records(id) on delete cascade,
  faculty text not null,
  subject text not null,
  section text not null,
  units integer,
  schedule text,
  created_at timestamp with time zone default now()
);

create table if not exists public.curriculum_subjects (
  code text primary key,
  title text not null,
  units integer,
  program text,
  year text,
  semester text,
  created_at timestamp with time zone default now()
);

create table if not exists public.enrollment_records (
  id text primary key,
  name text not null,
  program text,
  section text,
  status text,
  adviser text,
  created_at timestamp with time zone default now()
);

create table if not exists public.grade_sheets (
  id bigint generated by default as identity primary key,
  subject text not null,
  section text not null,
  period text not null,
  last_updated text,
  status text,
  created_at timestamp with time zone default now()
);

create table if not exists public.students (
  id text not null,
  name text not null,
  subj text not null,
  prof text not null,
  prelim integer,
  midterm integer,
  semi integer,
  final integer,
  status text,
  upload_method text,
  encoded_at timestamp with time zone,
  created_at timestamp with time zone default now(),
  primary key (id, subj)
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  code text not null,
  prof text not null,
  title text,
  created_at timestamp with time zone default now(),
  unique (code, prof)
);

create table if not exists public.user_profiles (
  id text primary key,
  name text not null,
  role text,
  avatar_url text,
  created_at timestamp with time zone default now()
);

alter table public.faculty_records enable row level security;
alter table public.teaching_loads enable row level security;
alter table public.curriculum_subjects enable row level security;
alter table public.enrollment_records enable row level security;
alter table public.grade_sheets enable row level security;
alter table public.subjects enable row level security;
alter table public.students enable row level security;
alter table public.user_profiles enable row level security;

-- Example read policies (adjust for your roles/claims)
drop policy if exists "faculty_records_read" on public.faculty_records;
create policy "faculty_records_read" on public.faculty_records
  for select using (true);

drop policy if exists "faculty_records_insert" on public.faculty_records;
create policy "faculty_records_insert" on public.faculty_records
  for insert with check (auth.jwt()->>'email' = id);

drop policy if exists "faculty_records_update" on public.faculty_records;
create policy "faculty_records_update" on public.faculty_records
  for update using (auth.jwt()->>'email' = id);

drop policy if exists "faculty_records_delete" on public.faculty_records;
create policy "faculty_records_delete" on public.faculty_records
  for delete using (
    auth.jwt()->>'email' = id
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "teaching_loads_read" on public.teaching_loads;
create policy "teaching_loads_read" on public.teaching_loads
  for select using (true);

drop policy if exists "curriculum_subjects_read" on public.curriculum_subjects;
create policy "curriculum_subjects_read" on public.curriculum_subjects
  for select using (true);

drop policy if exists "enrollment_records_read" on public.enrollment_records;
create policy "enrollment_records_read" on public.enrollment_records
  for select using (true);

drop policy if exists "grade_sheets_read" on public.grade_sheets;
create policy "grade_sheets_read" on public.grade_sheets
  for select using (true);

drop policy if exists "subjects_read" on public.subjects;
create policy "subjects_read" on public.subjects
  for select using (true);

drop policy if exists "subjects_insert" on public.subjects;
create policy "subjects_insert" on public.subjects
  for insert with check (auth.jwt()->>'email' = prof);

drop policy if exists "subjects_update" on public.subjects;
create policy "subjects_update" on public.subjects
  for update using (auth.jwt()->>'email' = prof);

drop policy if exists "subjects_delete" on public.subjects;
create policy "subjects_delete" on public.subjects
  for delete using (
    auth.jwt()->>'email' = prof
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "students_read" on public.students;
create policy "students_read" on public.students
  for select using (true);

drop policy if exists "students_insert" on public.students;
create policy "students_insert" on public.students
  for insert with check (auth.jwt()->>'email' = prof);

drop policy if exists "students_update" on public.students;
create policy "students_update" on public.students
  for update using (auth.jwt()->>'email' = prof);

drop policy if exists "students_delete" on public.students;
create policy "students_delete" on public.students
  for delete using (
    auth.jwt()->>'email' = prof
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "user_profiles_read" on public.user_profiles;
create policy "user_profiles_read" on public.user_profiles
  for select using (
    auth.jwt()->>'email' = id
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "user_profiles_insert" on public.user_profiles;
create policy "user_profiles_insert" on public.user_profiles
  for insert with check (
    auth.jwt()->>'email' = id
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );

drop policy if exists "user_profiles_update" on public.user_profiles;
create policy "user_profiles_update" on public.user_profiles
  for update using (
    auth.jwt()->>'email' = id
    OR auth.jwt()->'user_metadata'->>'role' = 'dean'
  );
